### ISSUE TITLE
issueベースの開発 * レビュー依頼

### ISSUE THREAD

**Issue by CarBoss1996** [CarBoss1996/kousienNow#31]
### MVPリリース時
 - [ ]　会員登録機能
 - [ ]　ログイン・ログアウト機能
 - [ ]　パスワード再設定機能
 - [ ]　ユーザー編集機能
 - [ ]　投稿機能
 - [ ]　投稿編集、削除機能
 - [ ]　投稿検索機能
 - [ ]　コメント機能
 - [ ]　通知機能
 - [ ]　位置情報取得機能
 - [ ]　位置情報表示機能
 - [ ]　位置情報に基づいたアイコンの表示機能
 - [ ]　座席情報機能
 - [ ]　座席情報に基づいた投稿の表示機能

### 本リリース時
 - [ ]　いいね機能
 - [ ]　いいね検索機能
 - [ ]　イベント機能
 - [ ]　観戦履歴機能
 - [ ]　メールアドレス変更機能
 - [ ]　SNSからの会員登録、ログイン機能

### 必要なページ
 - [ ]　トップページ
 - [ ]　会員登録ページ
 - [ ]　ログインページ
 - [ ]　ユーザー詳細ページ
 - [ ]　ユーザー情報編集ページ
 - [ ]　パスワード再設定ページ
 - [ ]　投稿ページ
 - [ ]　投稿一覧ページ
 - [ ]　投稿詳細ページ
 - [ ]　位置情報表示ページ
 - [ ]　位置情報登録ページ
 - [ ]　いいね一覧ページ
 - [ ]　座席一覧ページ
 - [ ]　座席詳細ページ
 - [ ]　お問い合わせ
 - [ ]　プライバシーポリシー
 - [ ]　利用規約

**Comment by CarBoss1996** [comment]
お世話になります。ISSUEの作成が完了いたしました。
お忙しいところ恐れ入りますが、ご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
![image](https://github.com/CarBoss1996/kousienNow/assets/61481161/39ef0bb6-59c3-468c-8800-c17f1f17550b)

projectsにアクセスしたところ、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、上記が確認できる状態でのご提出をお願いいたします。

**Comment by CarBoss1996** [comment]
すみません、Privateになっていたので、Publicにいたしました。
ご確認お願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！

ストーリーポイントに8がついているものがありますが、実装内容のイメージが出来ていないかissueにやることを詰め込みすぎなのかなと思いますので実装を進める前に一度どんな実装内容になるのかを調べて進めるとよいかなと思います
