### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by CarBoss1996** [CarBoss1996/kousienNow#65]
##各種情報
サービス名：甲子園NOW!
URL：https://kousiennow.onrender.com

## 概要
ISSUE面談後の技術面談にてMVPリリース要件を変更いたしました。

### MVPリリース時
 - [x] 会員登録機能
 - [x] ログイン・ログアウト機能
 - [x] パスワード再設定機能
 - [x] ユーザー編集機能
 - [x] 投稿機能
 - [x] 投稿編集、削除機能
 - [x] 位置情報登録機能
 - [x] 位置情報表示機能
 - [x] 位置情報に基づいたアイコンの表示機能
 - [x] Open Weather APIを使用した当日の天気を表示
 - [x] 当日の対戦相手、時間を表示

### 本リリース時
 - [ ]　Google Map APIを使用した 位置情報取得機能
 - [x] 投稿検索機能
 - [x] コメント機能
 - [x] いいね機能
 - [x] いいね検索機能
 - [ ]　座席情報機能
 - [ ]　座席情報に基づいた投稿の表示機能
 - [ ]　通知機能
 - [ ]　イベント機能
 - [ ]　観戦履歴機能
 - [ ]　メールアドレス変更機能
 - [ ]　SNSからの会員登録、ログイン機能

### 必要なページ
 - [x] トップページ
 - [x] 会員登録ページ
 - [x] ログインページ
 - [x] ユーザー詳細ページ
 - [x] ユーザー情報編集ページ
 - [x] パスワード再設定ページ
 - [x] 投稿ページ
 - [x] 投稿一覧ページ
 - [x] 投稿詳細ページ
 - [x] 位置情報表示ページ
 - [x] 位置情報登録ページ
 - [x] いいね一覧ページ
 - [ ]　座席一覧ページ
 - [ ]　座席詳細ページ
 - [ ]　お問い合わせ
 - [ ]　プライバシーポリシー
 - [ ]　利用規約

サービスイメージが分かるようなスクリーンショット等

| トップ画面 | 位置情報登録機能 |
|---|---|
|<a href="https://gyazo.com/05f8d70c90750676c0327a6dfdf58125"><img src="https://i.gyazo.com/05f8d70c90750676c0327a6dfdf58125.gif" alt="Image from Gyazo" width="400"/>|<a href="https://gyazo.com/2dc43b1c6c74a76ac56294318f170266"><img src="https://i.gyazo.com/2dc43b1c6c74a76ac56294318f170266.gif" alt="Image from Gyazo" width="400"/></a>
|---|---|
| 新規投稿機能 | アイコンから投稿の取得 |
|---|---|
|<a href="https://gyazo.com/7c6fd6b60c53a221400974885bcb6fbb"><img src="https://i.gyazo.com/7c6fd6b60c53a221400974885bcb6fbb.gif" alt="Image from Gyazo" width="400"/></a>|<a href="https://gyazo.com/b290fcb951642263063b5435fcdcdcdd"><img src="https://i.gyazo.com/b290fcb951642263063b5435fcdcdcdd.gif" alt="Image from Gyazo" width="400"/></a>|
|---|---|
| ユーザー詳細 | 投稿一覧 |
|---|---|
|<a href="https://gyazo.com/1eb3cecf9fc815b774d55bc75f8c9c77"><img src="https://i.gyazo.com/1eb3cecf9fc815b774d55bc75f8c9c77.png" alt="Image from Gyazo" width="400"/></a>|<a href="https://gyazo.com/a66cf985c0fbfe995771b444f9f7a7c4"><img src="https://i.gyazo.com/a66cf985c0fbfe995771b444f9f7a7c4.png" alt="Image from Gyazo" width="400"/></a>
|---|---|

**Comment by CarBoss1996** [comment]
お世話になります。５４期B川下です。
卒業制作のMVP要件を満たしたため、レビューお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！
